# Generated by Django 3.2 on 2023-03-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='User is considered as the inactive one unless he get the token.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='Yjsbfiv7364ksLfg89DgvHsl10', max_length=128, verbose_name='password'),
        ),
    ]
