# Generated by Django 3.2 on 2023-03-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='User is considered as the inactive one unless he get the token.', verbose_name='active'),
        ),
    ]
