# Generated by Django 3.2 on 2023-04-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_path', models.FileField(upload_to='static/data/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
