# Generated by Django 3.2 on 2023-04-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvimport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvimport',
            old_name='csv_path',
            new_name='csv_file',
        ),
    ]
